### PR TITLE
TBP: show file sizes, default to httpS and fix BeautifulSoup warnings

### PR DESCRIPTION
**Pull request by flurischt**

### CODE REVIEW

**Comment by DonDebonair** [comment]
Looks great! One question: why remove the specific lxml version? I'm fine with updating versions of dependencies of course, but being explicit about the version, makes sense to me, otherwise stuff can break when lxml releases a new version with breaking changes.

**Comment by flurischt** [comment]
Ah yeah, sorry for that. I removed the specific version to be able to install it using the package manager on my machine. This way I can use apt-get on my raspberry pi. With a specific version pip wants to compile lxml and this takes forever...

Should I readd lxml==3.6.1 as it was before?

**Comment by DonDebonair** [comment]
3.6.1 is a version I know to be working, but if the version apt-get installed for you is working as well, and is higher than 3.6.1, you can specify that version.

**Comment by flurischt** [comment]
My apt-get version is actually lower than that. I readded 3.6.1

**Comment by DonDebonair** [comment]
Thanks for the PR! Out of curiosity: what are you using it for? :)

**Comment by flurischt** [comment]
https://github.com/flurischt/habushu :)

**Comment by DonDebonair** [comment]
Nice, starred it! Will keep an eye on it :)

What version of lxml does apt-get install? I can change the requirements to specify that as a minimum version, so you can use the offical pypi `flood` package with the apt-get installed lxml.

**Comment by flurischt** [comment]
Nice! 

I run it using lxml==2.3.2 and had no problems so far.

**Comment by DonDebonair** [comment]
I've uploaded a new version to PyPI incl. your changes and a more lax lxml requirement, taking 2.3.2 as minimum. https://pypi.python.org/pypi/flood/0.6

**Comment by flurischt** [comment]
:ok_hand: thanks! I switched to using flood==0.6 from pypi.

**Pull request merged**
